# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
from . import _utilities
import typing
# Export this package's modules as members:
from .mysql_capsule import *
from .provider import *
from .redis_capsule import *
from .space import *
from .storage_capsule import *
from .team import *
from .wordpress_capsule import *

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_codecapsules.config as __config
    config = __config
else:
    config = _utilities.lazy_import('pulumi_codecapsules.config')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "codecapsules",
  "mod": "index",
  "fqn": "pulumi_codecapsules",
  "classes": {
   "codecapsules:index:MysqlCapsule": "MysqlCapsule",
   "codecapsules:index:RedisCapsule": "RedisCapsule",
   "codecapsules:index:Space": "Space",
   "codecapsules:index:StorageCapsule": "StorageCapsule",
   "codecapsules:index:Team": "Team",
   "codecapsules:index:WordpressCapsule": "WordpressCapsule"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "codecapsules",
  "token": "pulumi:providers:codecapsules",
  "fqn": "pulumi_codecapsules",
  "class": "Provider"
 }
]
"""
)
