# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['StorageCapsuleArgs', 'StorageCapsule']

@pulumi.input_type
class StorageCapsuleArgs:
    def __init__(__self__, *,
                 name: pulumi.Input[_builtins.str],
                 space_id: pulumi.Input[_builtins.str],
                 cpu_qty: Optional[pulumi.Input[_builtins.float]] = None,
                 cpu_unit: Optional[pulumi.Input[_builtins.str]] = None,
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 memory_qty: Optional[pulumi.Input[_builtins.float]] = None,
                 memory_unit: Optional[pulumi.Input[_builtins.str]] = None,
                 replicas: Optional[pulumi.Input[_builtins.int]] = None,
                 storage_qty: Optional[pulumi.Input[_builtins.float]] = None,
                 storage_unit: Optional[pulumi.Input[_builtins.str]] = None):
        """
        The set of arguments for constructing a StorageCapsule resource.
        :param pulumi.Input[_builtins.str] name: The capsule's name. Immutable after creation; changing it replaces the resource (renaming isn't supported).
        :param pulumi.Input[_builtins.str] space_id: The owning Space's id. Immutable after creation; changing it replaces the resource.
        :param pulumi.Input[_builtins.float] cpu_qty: CPU request quantity.
        :param pulumi.Input[_builtins.str] cpu_unit: CPU request unit, e.g. "m". Defaults to "m".
        :param pulumi.Input[_builtins.str] description: The capsule's description. Mutable in place.
        :param pulumi.Input[_builtins.float] memory_qty: Memory request quantity.
        :param pulumi.Input[_builtins.str] memory_unit: Memory request unit, e.g. "M". Defaults to "M".
        :param pulumi.Input[_builtins.int] replicas: Replica count. Defaults to 1.
        :param pulumi.Input[_builtins.float] storage_qty: Storage size requested. This is the primary sizing knob for a storage capsule.
        :param pulumi.Input[_builtins.str] storage_unit: Storage size unit, e.g. "Gi". Defaults to "Gi".
        """
        pulumi.set(__self__, "name", name)
        pulumi.set(__self__, "space_id", space_id)
        if cpu_qty is not None:
            pulumi.set(__self__, "cpu_qty", cpu_qty)
        if cpu_unit is not None:
            pulumi.set(__self__, "cpu_unit", cpu_unit)
        if description is not None:
            pulumi.set(__self__, "description", description)
        if memory_qty is not None:
            pulumi.set(__self__, "memory_qty", memory_qty)
        if memory_unit is not None:
            pulumi.set(__self__, "memory_unit", memory_unit)
        if replicas is not None:
            pulumi.set(__self__, "replicas", replicas)
        if storage_qty is not None:
            pulumi.set(__self__, "storage_qty", storage_qty)
        if storage_unit is not None:
            pulumi.set(__self__, "storage_unit", storage_unit)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[_builtins.str]:
        """
        The capsule's name. Immutable after creation; changing it replaces the resource (renaming isn't supported).
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter(name="spaceId")
    def space_id(self) -> pulumi.Input[_builtins.str]:
        """
        The owning Space's id. Immutable after creation; changing it replaces the resource.
        """
        return pulumi.get(self, "space_id")

    @space_id.setter
    def space_id(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "space_id", value)

    @_builtins.property
    @pulumi.getter(name="cpuQty")
    def cpu_qty(self) -> Optional[pulumi.Input[_builtins.float]]:
        """
        CPU request quantity.
        """
        return pulumi.get(self, "cpu_qty")

    @cpu_qty.setter
    def cpu_qty(self, value: Optional[pulumi.Input[_builtins.float]]):
        pulumi.set(self, "cpu_qty", value)

    @_builtins.property
    @pulumi.getter(name="cpuUnit")
    def cpu_unit(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        CPU request unit, e.g. "m". Defaults to "m".
        """
        return pulumi.get(self, "cpu_unit")

    @cpu_unit.setter
    def cpu_unit(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "cpu_unit", value)

    @_builtins.property
    @pulumi.getter
    def description(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The capsule's description. Mutable in place.
        """
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "description", value)

    @_builtins.property
    @pulumi.getter(name="memoryQty")
    def memory_qty(self) -> Optional[pulumi.Input[_builtins.float]]:
        """
        Memory request quantity.
        """
        return pulumi.get(self, "memory_qty")

    @memory_qty.setter
    def memory_qty(self, value: Optional[pulumi.Input[_builtins.float]]):
        pulumi.set(self, "memory_qty", value)

    @_builtins.property
    @pulumi.getter(name="memoryUnit")
    def memory_unit(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Memory request unit, e.g. "M". Defaults to "M".
        """
        return pulumi.get(self, "memory_unit")

    @memory_unit.setter
    def memory_unit(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "memory_unit", value)

    @_builtins.property
    @pulumi.getter
    def replicas(self) -> Optional[pulumi.Input[_builtins.int]]:
        """
        Replica count. Defaults to 1.
        """
        return pulumi.get(self, "replicas")

    @replicas.setter
    def replicas(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "replicas", value)

    @_builtins.property
    @pulumi.getter(name="storageQty")
    def storage_qty(self) -> Optional[pulumi.Input[_builtins.float]]:
        """
        Storage size requested. This is the primary sizing knob for a storage capsule.
        """
        return pulumi.get(self, "storage_qty")

    @storage_qty.setter
    def storage_qty(self, value: Optional[pulumi.Input[_builtins.float]]):
        pulumi.set(self, "storage_qty", value)

    @_builtins.property
    @pulumi.getter(name="storageUnit")
    def storage_unit(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Storage size unit, e.g. "Gi". Defaults to "Gi".
        """
        return pulumi.get(self, "storage_unit")

    @storage_unit.setter
    def storage_unit(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "storage_unit", value)


@pulumi.type_token("codecapsules:index:StorageCapsule")
class StorageCapsule(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 cpu_qty: Optional[pulumi.Input[_builtins.float]] = None,
                 cpu_unit: Optional[pulumi.Input[_builtins.str]] = None,
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 memory_qty: Optional[pulumi.Input[_builtins.float]] = None,
                 memory_unit: Optional[pulumi.Input[_builtins.str]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 replicas: Optional[pulumi.Input[_builtins.int]] = None,
                 space_id: Optional[pulumi.Input[_builtins.str]] = None,
                 storage_qty: Optional[pulumi.Input[_builtins.float]] = None,
                 storage_unit: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        """
        Create a StorageCapsule resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.float] cpu_qty: CPU request quantity.
        :param pulumi.Input[_builtins.str] cpu_unit: CPU request unit, e.g. "m". Defaults to "m".
        :param pulumi.Input[_builtins.str] description: The capsule's description. Mutable in place.
        :param pulumi.Input[_builtins.float] memory_qty: Memory request quantity.
        :param pulumi.Input[_builtins.str] memory_unit: Memory request unit, e.g. "M". Defaults to "M".
        :param pulumi.Input[_builtins.str] name: The capsule's name. Immutable after creation; changing it replaces the resource (renaming isn't supported).
        :param pulumi.Input[_builtins.int] replicas: Replica count. Defaults to 1.
        :param pulumi.Input[_builtins.str] space_id: The owning Space's id. Immutable after creation; changing it replaces the resource.
        :param pulumi.Input[_builtins.float] storage_qty: Storage size requested. This is the primary sizing knob for a storage capsule.
        :param pulumi.Input[_builtins.str] storage_unit: Storage size unit, e.g. "Gi". Defaults to "Gi".
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: StorageCapsuleArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a StorageCapsule resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param StorageCapsuleArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(StorageCapsuleArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 cpu_qty: Optional[pulumi.Input[_builtins.float]] = None,
                 cpu_unit: Optional[pulumi.Input[_builtins.str]] = None,
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 memory_qty: Optional[pulumi.Input[_builtins.float]] = None,
                 memory_unit: Optional[pulumi.Input[_builtins.str]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 replicas: Optional[pulumi.Input[_builtins.int]] = None,
                 space_id: Optional[pulumi.Input[_builtins.str]] = None,
                 storage_qty: Optional[pulumi.Input[_builtins.float]] = None,
                 storage_unit: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = StorageCapsuleArgs.__new__(StorageCapsuleArgs)

            __props__.__dict__["cpu_qty"] = cpu_qty
            __props__.__dict__["cpu_unit"] = cpu_unit
            __props__.__dict__["description"] = description
            __props__.__dict__["memory_qty"] = memory_qty
            __props__.__dict__["memory_unit"] = memory_unit
            if name is None and not opts.urn:
                raise TypeError("Missing required property 'name'")
            __props__.__dict__["name"] = name
            __props__.__dict__["replicas"] = replicas
            if space_id is None and not opts.urn:
                raise TypeError("Missing required property 'space_id'")
            __props__.__dict__["space_id"] = space_id
            __props__.__dict__["storage_qty"] = storage_qty
            __props__.__dict__["storage_unit"] = storage_unit
        super(StorageCapsule, __self__).__init__(
            'codecapsules:index:StorageCapsule',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None) -> 'StorageCapsule':
        """
        Get an existing StorageCapsule resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = StorageCapsuleArgs.__new__(StorageCapsuleArgs)

        __props__.__dict__["cpu_qty"] = None
        __props__.__dict__["cpu_unit"] = None
        __props__.__dict__["description"] = None
        __props__.__dict__["memory_qty"] = None
        __props__.__dict__["memory_unit"] = None
        __props__.__dict__["name"] = None
        __props__.__dict__["replicas"] = None
        __props__.__dict__["space_id"] = None
        __props__.__dict__["storage_qty"] = None
        __props__.__dict__["storage_unit"] = None
        return StorageCapsule(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="cpuQty")
    def cpu_qty(self) -> pulumi.Output[_builtins.float]:
        return pulumi.get(self, "cpu_qty")

    @_builtins.property
    @pulumi.getter(name="cpuUnit")
    def cpu_unit(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "cpu_unit")

    @_builtins.property
    @pulumi.getter
    def description(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "description")

    @_builtins.property
    @pulumi.getter(name="memoryQty")
    def memory_qty(self) -> pulumi.Output[_builtins.float]:
        return pulumi.get(self, "memory_qty")

    @_builtins.property
    @pulumi.getter(name="memoryUnit")
    def memory_unit(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "memory_unit")

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter
    def replicas(self) -> pulumi.Output[_builtins.int]:
        return pulumi.get(self, "replicas")

    @_builtins.property
    @pulumi.getter(name="spaceId")
    def space_id(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "space_id")

    @_builtins.property
    @pulumi.getter(name="storageQty")
    def storage_qty(self) -> pulumi.Output[_builtins.float]:
        return pulumi.get(self, "storage_qty")

    @_builtins.property
    @pulumi.getter(name="storageUnit")
    def storage_unit(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "storage_unit")

