# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['WordpressCapsuleArgs', 'WordpressCapsule']

@pulumi.input_type
class WordpressCapsuleArgs:
    def __init__(__self__, *,
                 database_name: pulumi.Input[_builtins.str],
                 mysql_capsule_id: pulumi.Input[_builtins.str],
                 name: pulumi.Input[_builtins.str],
                 space_id: pulumi.Input[_builtins.str],
                 storage_capsule_id: pulumi.Input[_builtins.str],
                 branch: Optional[pulumi.Input[_builtins.str]] = None,
                 cpu_qty: Optional[pulumi.Input[_builtins.float]] = None,
                 cpu_unit: Optional[pulumi.Input[_builtins.str]] = None,
                 deployment_type: Optional[pulumi.Input[_builtins.str]] = None,
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 env: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 git_repository_id: Optional[pulumi.Input[_builtins.str]] = None,
                 memory_qty: Optional[pulumi.Input[_builtins.float]] = None,
                 memory_unit: Optional[pulumi.Input[_builtins.str]] = None,
                 replicas: Optional[pulumi.Input[_builtins.int]] = None,
                 source_subpath: Optional[pulumi.Input[_builtins.str]] = None,
                 storage_qty: Optional[pulumi.Input[_builtins.float]] = None,
                 storage_unit: Optional[pulumi.Input[_builtins.str]] = None,
                 version: Optional[pulumi.Input[_builtins.str]] = None):
        """
        The set of arguments for constructing a WordpressCapsule resource.
        :param pulumi.Input[_builtins.str] database_name: The database name to use on the referenced MysqlCapsule. Immutable after creation; changing it replaces the resource.
        :param pulumi.Input[_builtins.str] mysql_capsule_id: The id of an existing MysqlCapsule (must already be Ready) this site's database. Immutable after creation; changing it replaces the resource.
        :param pulumi.Input[_builtins.str] name: The capsule's name. Immutable after creation; changing it replaces the resource (renaming isn't supported).
        :param pulumi.Input[_builtins.str] space_id: The owning Space's id. Immutable after creation; changing it replaces the resource.
        :param pulumi.Input[_builtins.str] storage_capsule_id: The id of an existing StorageCapsule for this site's uploads/media. Immutable after creation; changing it replaces the resource.
        :param pulumi.Input[_builtins.str] branch: The branch to deploy from. Required when deploymentType is "git", unused for "default". Immutable after creation; changing it replaces the resource. Note: creating a "git" capsule does not deploy anything by itself - the site goes live on the next push to this branch.
        :param pulumi.Input[_builtins.float] cpu_qty: CPU request quantity.
        :param pulumi.Input[_builtins.str] cpu_unit: CPU request unit, e.g. "m". Defaults to "m".
        :param pulumi.Input[_builtins.str] deployment_type: Deployment type: "default" (stock WordPress version/image) or "git" (custom codebase from an already-connected repository). Defaults to "default". Immutable after creation.
        :param pulumi.Input[_builtins.str] description: The capsule's description. Mutable in place.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] env: Environment variables for the capsule. Replaces the full set on every change - useful for wiring in a RedisCapsule's connection details.
        :param pulumi.Input[_builtins.str] git_repository_id: The id of a git repository already connected to Code Capsules (connect it via the dashboard first - this resource can only reference an existing connection, not create one). Required when deploymentType is "git", unused for "default". Immutable after creation; changing it replaces the resource.
        :param pulumi.Input[_builtins.float] memory_qty: Memory request quantity.
        :param pulumi.Input[_builtins.str] memory_unit: Memory request unit, e.g. "M". Defaults to "M".
        :param pulumi.Input[_builtins.int] replicas: Replica count. Defaults to 1.
        :param pulumi.Input[_builtins.str] source_subpath: Subpath within the repository where the WordPress root lives, for repositories that aren't WordPress at their root. Optional in either deployment mode. Immutable after creation; changing it replaces the resource.
        :param pulumi.Input[_builtins.float] storage_qty: Storage request quantity.
        :param pulumi.Input[_builtins.str] storage_unit: Storage request unit, e.g. "Gi". Defaults to "Gi".
        :param pulumi.Input[_builtins.str] version: The WordPress version to deploy. Required when deploymentType is "default", unused for "git". Immutable after creation; changing it replaces the resource.
        """
        pulumi.set(__self__, "database_name", database_name)
        pulumi.set(__self__, "mysql_capsule_id", mysql_capsule_id)
        pulumi.set(__self__, "name", name)
        pulumi.set(__self__, "space_id", space_id)
        pulumi.set(__self__, "storage_capsule_id", storage_capsule_id)
        if branch is not None:
            pulumi.set(__self__, "branch", branch)
        if cpu_qty is not None:
            pulumi.set(__self__, "cpu_qty", cpu_qty)
        if cpu_unit is not None:
            pulumi.set(__self__, "cpu_unit", cpu_unit)
        if deployment_type is not None:
            pulumi.set(__self__, "deployment_type", deployment_type)
        if description is not None:
            pulumi.set(__self__, "description", description)
        if env is not None:
            pulumi.set(__self__, "env", env)
        if git_repository_id is not None:
            pulumi.set(__self__, "git_repository_id", git_repository_id)
        if memory_qty is not None:
            pulumi.set(__self__, "memory_qty", memory_qty)
        if memory_unit is not None:
            pulumi.set(__self__, "memory_unit", memory_unit)
        if replicas is not None:
            pulumi.set(__self__, "replicas", replicas)
        if source_subpath is not None:
            pulumi.set(__self__, "source_subpath", source_subpath)
        if storage_qty is not None:
            pulumi.set(__self__, "storage_qty", storage_qty)
        if storage_unit is not None:
            pulumi.set(__self__, "storage_unit", storage_unit)
        if version is not None:
            pulumi.set(__self__, "version", version)

    @_builtins.property
    @pulumi.getter(name="databaseName")
    def database_name(self) -> pulumi.Input[_builtins.str]:
        """
        The database name to use on the referenced MysqlCapsule. Immutable after creation; changing it replaces the resource.
        """
        return pulumi.get(self, "database_name")

    @database_name.setter
    def database_name(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "database_name", value)

    @_builtins.property
    @pulumi.getter(name="mysqlCapsuleId")
    def mysql_capsule_id(self) -> pulumi.Input[_builtins.str]:
        """
        The id of an existing MysqlCapsule (must already be Ready) this site's database. Immutable after creation; changing it replaces the resource.
        """
        return pulumi.get(self, "mysql_capsule_id")

    @mysql_capsule_id.setter
    def mysql_capsule_id(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "mysql_capsule_id", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[_builtins.str]:
        """
        The capsule's name. Immutable after creation; changing it replaces the resource (renaming isn't supported).
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter(name="spaceId")
    def space_id(self) -> pulumi.Input[_builtins.str]:
        """
        The owning Space's id. Immutable after creation; changing it replaces the resource.
        """
        return pulumi.get(self, "space_id")

    @space_id.setter
    def space_id(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "space_id", value)

    @_builtins.property
    @pulumi.getter(name="storageCapsuleId")
    def storage_capsule_id(self) -> pulumi.Input[_builtins.str]:
        """
        The id of an existing StorageCapsule for this site's uploads/media. Immutable after creation; changing it replaces the resource.
        """
        return pulumi.get(self, "storage_capsule_id")

    @storage_capsule_id.setter
    def storage_capsule_id(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "storage_capsule_id", value)

    @_builtins.property
    @pulumi.getter
    def branch(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The branch to deploy from. Required when deploymentType is "git", unused for "default". Immutable after creation; changing it replaces the resource. Note: creating a "git" capsule does not deploy anything by itself - the site goes live on the next push to this branch.
        """
        return pulumi.get(self, "branch")

    @branch.setter
    def branch(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "branch", value)

    @_builtins.property
    @pulumi.getter(name="cpuQty")
    def cpu_qty(self) -> Optional[pulumi.Input[_builtins.float]]:
        """
        CPU request quantity.
        """
        return pulumi.get(self, "cpu_qty")

    @cpu_qty.setter
    def cpu_qty(self, value: Optional[pulumi.Input[_builtins.float]]):
        pulumi.set(self, "cpu_qty", value)

    @_builtins.property
    @pulumi.getter(name="cpuUnit")
    def cpu_unit(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        CPU request unit, e.g. "m". Defaults to "m".
        """
        return pulumi.get(self, "cpu_unit")

    @cpu_unit.setter
    def cpu_unit(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "cpu_unit", value)

    @_builtins.property
    @pulumi.getter(name="deploymentType")
    def deployment_type(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Deployment type: "default" (stock WordPress version/image) or "git" (custom codebase from an already-connected repository). Defaults to "default". Immutable after creation.
        """
        return pulumi.get(self, "deployment_type")

    @deployment_type.setter
    def deployment_type(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "deployment_type", value)

    @_builtins.property
    @pulumi.getter
    def description(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The capsule's description. Mutable in place.
        """
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "description", value)

    @_builtins.property
    @pulumi.getter
    def env(self) -> Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]:
        """
        Environment variables for the capsule. Replaces the full set on every change - useful for wiring in a RedisCapsule's connection details.
        """
        return pulumi.get(self, "env")

    @env.setter
    def env(self, value: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "env", value)

    @_builtins.property
    @pulumi.getter(name="gitRepositoryId")
    def git_repository_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The id of a git repository already connected to Code Capsules (connect it via the dashboard first - this resource can only reference an existing connection, not create one). Required when deploymentType is "git", unused for "default". Immutable after creation; changing it replaces the resource.
        """
        return pulumi.get(self, "git_repository_id")

    @git_repository_id.setter
    def git_repository_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "git_repository_id", value)

    @_builtins.property
    @pulumi.getter(name="memoryQty")
    def memory_qty(self) -> Optional[pulumi.Input[_builtins.float]]:
        """
        Memory request quantity.
        """
        return pulumi.get(self, "memory_qty")

    @memory_qty.setter
    def memory_qty(self, value: Optional[pulumi.Input[_builtins.float]]):
        pulumi.set(self, "memory_qty", value)

    @_builtins.property
    @pulumi.getter(name="memoryUnit")
    def memory_unit(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Memory request unit, e.g. "M". Defaults to "M".
        """
        return pulumi.get(self, "memory_unit")

    @memory_unit.setter
    def memory_unit(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "memory_unit", value)

    @_builtins.property
    @pulumi.getter
    def replicas(self) -> Optional[pulumi.Input[_builtins.int]]:
        """
        Replica count. Defaults to 1.
        """
        return pulumi.get(self, "replicas")

    @replicas.setter
    def replicas(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "replicas", value)

    @_builtins.property
    @pulumi.getter(name="sourceSubpath")
    def source_subpath(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Subpath within the repository where the WordPress root lives, for repositories that aren't WordPress at their root. Optional in either deployment mode. Immutable after creation; changing it replaces the resource.
        """
        return pulumi.get(self, "source_subpath")

    @source_subpath.setter
    def source_subpath(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "source_subpath", value)

    @_builtins.property
    @pulumi.getter(name="storageQty")
    def storage_qty(self) -> Optional[pulumi.Input[_builtins.float]]:
        """
        Storage request quantity.
        """
        return pulumi.get(self, "storage_qty")

    @storage_qty.setter
    def storage_qty(self, value: Optional[pulumi.Input[_builtins.float]]):
        pulumi.set(self, "storage_qty", value)

    @_builtins.property
    @pulumi.getter(name="storageUnit")
    def storage_unit(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Storage request unit, e.g. "Gi". Defaults to "Gi".
        """
        return pulumi.get(self, "storage_unit")

    @storage_unit.setter
    def storage_unit(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "storage_unit", value)

    @_builtins.property
    @pulumi.getter
    def version(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The WordPress version to deploy. Required when deploymentType is "default", unused for "git". Immutable after creation; changing it replaces the resource.
        """
        return pulumi.get(self, "version")

    @version.setter
    def version(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "version", value)


@pulumi.type_token("codecapsules:index:WordpressCapsule")
class WordpressCapsule(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 branch: Optional[pulumi.Input[_builtins.str]] = None,
                 cpu_qty: Optional[pulumi.Input[_builtins.float]] = None,
                 cpu_unit: Optional[pulumi.Input[_builtins.str]] = None,
                 database_name: Optional[pulumi.Input[_builtins.str]] = None,
                 deployment_type: Optional[pulumi.Input[_builtins.str]] = None,
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 env: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 git_repository_id: Optional[pulumi.Input[_builtins.str]] = None,
                 memory_qty: Optional[pulumi.Input[_builtins.float]] = None,
                 memory_unit: Optional[pulumi.Input[_builtins.str]] = None,
                 mysql_capsule_id: Optional[pulumi.Input[_builtins.str]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 replicas: Optional[pulumi.Input[_builtins.int]] = None,
                 source_subpath: Optional[pulumi.Input[_builtins.str]] = None,
                 space_id: Optional[pulumi.Input[_builtins.str]] = None,
                 storage_capsule_id: Optional[pulumi.Input[_builtins.str]] = None,
                 storage_qty: Optional[pulumi.Input[_builtins.float]] = None,
                 storage_unit: Optional[pulumi.Input[_builtins.str]] = None,
                 version: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        """
        Create a WordpressCapsule resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] branch: The branch to deploy from. Required when deploymentType is "git", unused for "default". Immutable after creation; changing it replaces the resource. Note: creating a "git" capsule does not deploy anything by itself - the site goes live on the next push to this branch.
        :param pulumi.Input[_builtins.float] cpu_qty: CPU request quantity.
        :param pulumi.Input[_builtins.str] cpu_unit: CPU request unit, e.g. "m". Defaults to "m".
        :param pulumi.Input[_builtins.str] database_name: The database name to use on the referenced MysqlCapsule. Immutable after creation; changing it replaces the resource.
        :param pulumi.Input[_builtins.str] deployment_type: Deployment type: "default" (stock WordPress version/image) or "git" (custom codebase from an already-connected repository). Defaults to "default". Immutable after creation.
        :param pulumi.Input[_builtins.str] description: The capsule's description. Mutable in place.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] env: Environment variables for the capsule. Replaces the full set on every change - useful for wiring in a RedisCapsule's connection details.
        :param pulumi.Input[_builtins.str] git_repository_id: The id of a git repository already connected to Code Capsules (connect it via the dashboard first - this resource can only reference an existing connection, not create one). Required when deploymentType is "git", unused for "default". Immutable after creation; changing it replaces the resource.
        :param pulumi.Input[_builtins.float] memory_qty: Memory request quantity.
        :param pulumi.Input[_builtins.str] memory_unit: Memory request unit, e.g. "M". Defaults to "M".
        :param pulumi.Input[_builtins.str] mysql_capsule_id: The id of an existing MysqlCapsule (must already be Ready) this site's database. Immutable after creation; changing it replaces the resource.
        :param pulumi.Input[_builtins.str] name: The capsule's name. Immutable after creation; changing it replaces the resource (renaming isn't supported).
        :param pulumi.Input[_builtins.int] replicas: Replica count. Defaults to 1.
        :param pulumi.Input[_builtins.str] source_subpath: Subpath within the repository where the WordPress root lives, for repositories that aren't WordPress at their root. Optional in either deployment mode. Immutable after creation; changing it replaces the resource.
        :param pulumi.Input[_builtins.str] space_id: The owning Space's id. Immutable after creation; changing it replaces the resource.
        :param pulumi.Input[_builtins.str] storage_capsule_id: The id of an existing StorageCapsule for this site's uploads/media. Immutable after creation; changing it replaces the resource.
        :param pulumi.Input[_builtins.float] storage_qty: Storage request quantity.
        :param pulumi.Input[_builtins.str] storage_unit: Storage request unit, e.g. "Gi". Defaults to "Gi".
        :param pulumi.Input[_builtins.str] version: The WordPress version to deploy. Required when deploymentType is "default", unused for "git". Immutable after creation; changing it replaces the resource.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: WordpressCapsuleArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a WordpressCapsule resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param WordpressCapsuleArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(WordpressCapsuleArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 branch: Optional[pulumi.Input[_builtins.str]] = None,
                 cpu_qty: Optional[pulumi.Input[_builtins.float]] = None,
                 cpu_unit: Optional[pulumi.Input[_builtins.str]] = None,
                 database_name: Optional[pulumi.Input[_builtins.str]] = None,
                 deployment_type: Optional[pulumi.Input[_builtins.str]] = None,
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 env: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 git_repository_id: Optional[pulumi.Input[_builtins.str]] = None,
                 memory_qty: Optional[pulumi.Input[_builtins.float]] = None,
                 memory_unit: Optional[pulumi.Input[_builtins.str]] = None,
                 mysql_capsule_id: Optional[pulumi.Input[_builtins.str]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 replicas: Optional[pulumi.Input[_builtins.int]] = None,
                 source_subpath: Optional[pulumi.Input[_builtins.str]] = None,
                 space_id: Optional[pulumi.Input[_builtins.str]] = None,
                 storage_capsule_id: Optional[pulumi.Input[_builtins.str]] = None,
                 storage_qty: Optional[pulumi.Input[_builtins.float]] = None,
                 storage_unit: Optional[pulumi.Input[_builtins.str]] = None,
                 version: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = WordpressCapsuleArgs.__new__(WordpressCapsuleArgs)

            __props__.__dict__["branch"] = branch
            __props__.__dict__["cpu_qty"] = cpu_qty
            __props__.__dict__["cpu_unit"] = cpu_unit
            if database_name is None and not opts.urn:
                raise TypeError("Missing required property 'database_name'")
            __props__.__dict__["database_name"] = database_name
            __props__.__dict__["deployment_type"] = deployment_type
            __props__.__dict__["description"] = description
            __props__.__dict__["env"] = None if env is None else pulumi.Output.secret(env)
            __props__.__dict__["git_repository_id"] = git_repository_id
            __props__.__dict__["memory_qty"] = memory_qty
            __props__.__dict__["memory_unit"] = memory_unit
            if mysql_capsule_id is None and not opts.urn:
                raise TypeError("Missing required property 'mysql_capsule_id'")
            __props__.__dict__["mysql_capsule_id"] = mysql_capsule_id
            if name is None and not opts.urn:
                raise TypeError("Missing required property 'name'")
            __props__.__dict__["name"] = name
            __props__.__dict__["replicas"] = replicas
            __props__.__dict__["source_subpath"] = source_subpath
            if space_id is None and not opts.urn:
                raise TypeError("Missing required property 'space_id'")
            __props__.__dict__["space_id"] = space_id
            if storage_capsule_id is None and not opts.urn:
                raise TypeError("Missing required property 'storage_capsule_id'")
            __props__.__dict__["storage_capsule_id"] = storage_capsule_id
            __props__.__dict__["storage_qty"] = storage_qty
            __props__.__dict__["storage_unit"] = storage_unit
            __props__.__dict__["version"] = version
            __props__.__dict__["hostname"] = None
        secret_opts = pulumi.ResourceOptions(additional_secret_outputs=["env"])
        opts = pulumi.ResourceOptions.merge(opts, secret_opts)
        super(WordpressCapsule, __self__).__init__(
            'codecapsules:index:WordpressCapsule',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None) -> 'WordpressCapsule':
        """
        Get an existing WordpressCapsule resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = WordpressCapsuleArgs.__new__(WordpressCapsuleArgs)

        __props__.__dict__["branch"] = None
        __props__.__dict__["cpu_qty"] = None
        __props__.__dict__["cpu_unit"] = None
        __props__.__dict__["database_name"] = None
        __props__.__dict__["deployment_type"] = None
        __props__.__dict__["description"] = None
        __props__.__dict__["env"] = None
        __props__.__dict__["git_repository_id"] = None
        __props__.__dict__["hostname"] = None
        __props__.__dict__["memory_qty"] = None
        __props__.__dict__["memory_unit"] = None
        __props__.__dict__["mysql_capsule_id"] = None
        __props__.__dict__["name"] = None
        __props__.__dict__["replicas"] = None
        __props__.__dict__["source_subpath"] = None
        __props__.__dict__["space_id"] = None
        __props__.__dict__["storage_capsule_id"] = None
        __props__.__dict__["storage_qty"] = None
        __props__.__dict__["storage_unit"] = None
        __props__.__dict__["version"] = None
        return WordpressCapsule(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter
    def branch(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "branch")

    @_builtins.property
    @pulumi.getter(name="cpuQty")
    def cpu_qty(self) -> pulumi.Output[_builtins.float]:
        return pulumi.get(self, "cpu_qty")

    @_builtins.property
    @pulumi.getter(name="cpuUnit")
    def cpu_unit(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "cpu_unit")

    @_builtins.property
    @pulumi.getter(name="databaseName")
    def database_name(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "database_name")

    @_builtins.property
    @pulumi.getter(name="deploymentType")
    def deployment_type(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "deployment_type")

    @_builtins.property
    @pulumi.getter
    def description(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "description")

    @_builtins.property
    @pulumi.getter
    def env(self) -> pulumi.Output[Optional[Mapping[str, _builtins.str]]]:
        return pulumi.get(self, "env")

    @_builtins.property
    @pulumi.getter(name="gitRepositoryId")
    def git_repository_id(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "git_repository_id")

    @_builtins.property
    @pulumi.getter
    def hostname(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "hostname")

    @_builtins.property
    @pulumi.getter(name="memoryQty")
    def memory_qty(self) -> pulumi.Output[_builtins.float]:
        return pulumi.get(self, "memory_qty")

    @_builtins.property
    @pulumi.getter(name="memoryUnit")
    def memory_unit(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "memory_unit")

    @_builtins.property
    @pulumi.getter(name="mysqlCapsuleId")
    def mysql_capsule_id(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "mysql_capsule_id")

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter
    def replicas(self) -> pulumi.Output[_builtins.int]:
        return pulumi.get(self, "replicas")

    @_builtins.property
    @pulumi.getter(name="sourceSubpath")
    def source_subpath(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "source_subpath")

    @_builtins.property
    @pulumi.getter(name="spaceId")
    def space_id(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "space_id")

    @_builtins.property
    @pulumi.getter(name="storageCapsuleId")
    def storage_capsule_id(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "storage_capsule_id")

    @_builtins.property
    @pulumi.getter(name="storageQty")
    def storage_qty(self) -> pulumi.Output[_builtins.float]:
        return pulumi.get(self, "storage_qty")

    @_builtins.property
    @pulumi.getter(name="storageUnit")
    def storage_unit(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "storage_unit")

    @_builtins.property
    @pulumi.getter
    def version(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "version")

