// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

// Export members:
export { MysqlCapsuleArgs } from "./mysqlCapsule";
export type MysqlCapsule = import("./mysqlCapsule").MysqlCapsule;
export const MysqlCapsule: typeof import("./mysqlCapsule").MysqlCapsule = null as any;
utilities.lazyLoad(exports, ["MysqlCapsule"], () => require("./mysqlCapsule"));

export { ProviderArgs } from "./provider";
export type Provider = import("./provider").Provider;
export const Provider: typeof import("./provider").Provider = null as any;
utilities.lazyLoad(exports, ["Provider"], () => require("./provider"));

export { RedisCapsuleArgs } from "./redisCapsule";
export type RedisCapsule = import("./redisCapsule").RedisCapsule;
export const RedisCapsule: typeof import("./redisCapsule").RedisCapsule = null as any;
utilities.lazyLoad(exports, ["RedisCapsule"], () => require("./redisCapsule"));

export { SpaceArgs } from "./space";
export type Space = import("./space").Space;
export const Space: typeof import("./space").Space = null as any;
utilities.lazyLoad(exports, ["Space"], () => require("./space"));

export { StorageCapsuleArgs } from "./storageCapsule";
export type StorageCapsule = import("./storageCapsule").StorageCapsule;
export const StorageCapsule: typeof import("./storageCapsule").StorageCapsule = null as any;
utilities.lazyLoad(exports, ["StorageCapsule"], () => require("./storageCapsule"));

export { TeamArgs } from "./team";
export type Team = import("./team").Team;
export const Team: typeof import("./team").Team = null as any;
utilities.lazyLoad(exports, ["Team"], () => require("./team"));

export { WordpressCapsuleArgs } from "./wordpressCapsule";
export type WordpressCapsule = import("./wordpressCapsule").WordpressCapsule;
export const WordpressCapsule: typeof import("./wordpressCapsule").WordpressCapsule = null as any;
utilities.lazyLoad(exports, ["WordpressCapsule"], () => require("./wordpressCapsule"));


// Export sub-modules:
import * as config from "./config";

export {
    config,
};

const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "codecapsules:index:MysqlCapsule":
                return new MysqlCapsule(name, <any>undefined, { urn })
            case "codecapsules:index:RedisCapsule":
                return new RedisCapsule(name, <any>undefined, { urn })
            case "codecapsules:index:Space":
                return new Space(name, <any>undefined, { urn })
            case "codecapsules:index:StorageCapsule":
                return new StorageCapsule(name, <any>undefined, { urn })
            case "codecapsules:index:Team":
                return new Team(name, <any>undefined, { urn })
            case "codecapsules:index:WordpressCapsule":
                return new WordpressCapsule(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("codecapsules", "index", _module)
pulumi.runtime.registerResourcePackage("codecapsules", {
    version: utilities.getVersion(),
    constructProvider: (name: string, type: string, urn: string): pulumi.ProviderResource => {
        if (type !== "pulumi:providers:codecapsules") {
            throw new Error(`unknown provider type ${type}`);
        }
        return new Provider(name, <any>undefined, { urn });
    },
});
