// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class Provider extends pulumi.ProviderResource {
    /** @internal */
    public static readonly __pulumiType = 'codecapsules';

    /**
     * Returns true if the given object is an instance of Provider.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Provider {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === "pulumi:providers:" + Provider.__pulumiType;
    }

    declare public readonly apiKey: pulumi.Output<string | undefined>;
    declare public readonly apiUrl: pulumi.Output<string | undefined>;
    declare public readonly authApiKey: pulumi.Output<string | undefined>;
    declare public readonly authBaseUrl: pulumi.Output<string | undefined>;
    declare public readonly email: pulumi.Output<string | undefined>;
    declare public readonly password: pulumi.Output<string | undefined>;

    /**
     * Create a Provider resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: ProviderArgs, opts?: pulumi.ResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        {
            resourceInputs["apiKey"] = args?.apiKey ? pulumi.secret(args.apiKey) : undefined;
            resourceInputs["apiUrl"] = args?.apiUrl;
            resourceInputs["authApiKey"] = args?.authApiKey ? pulumi.secret(args.authApiKey) : undefined;
            resourceInputs["authBaseUrl"] = args?.authBaseUrl;
            resourceInputs["email"] = args?.email;
            resourceInputs["password"] = args?.password ? pulumi.secret(args.password) : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["apiKey", "authApiKey", "password"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(Provider.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a Provider resource.
 */
export interface ProviderArgs {
    apiKey?: pulumi.Input<string>;
    apiUrl?: pulumi.Input<string>;
    authApiKey?: pulumi.Input<string>;
    authBaseUrl?: pulumi.Input<string>;
    email?: pulumi.Input<string>;
    password?: pulumi.Input<string>;
}
