// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class RedisCapsule extends pulumi.CustomResource {
    /**
     * Get an existing RedisCapsule resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): RedisCapsule {
        return new RedisCapsule(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'codecapsules:index:RedisCapsule';

    /**
     * Returns true if the given object is an instance of RedisCapsule.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is RedisCapsule {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === RedisCapsule.__pulumiType;
    }

    declare public readonly cpuQty: pulumi.Output<number>;
    declare public readonly cpuUnit: pulumi.Output<string>;
    declare public readonly description: pulumi.Output<string>;
    declare public readonly memoryQty: pulumi.Output<number>;
    declare public readonly memoryUnit: pulumi.Output<string>;
    declare public readonly name: pulumi.Output<string>;
    declare public /*out*/ readonly privateConnectionString: pulumi.Output<string>;
    declare public /*out*/ readonly privateHostname: pulumi.Output<string>;
    declare public /*out*/ readonly privatePort: pulumi.Output<string>;
    declare public readonly replicas: pulumi.Output<number>;
    declare public readonly spaceId: pulumi.Output<string>;
    declare public readonly storageQty: pulumi.Output<number>;
    declare public readonly storageUnit: pulumi.Output<string>;

    /**
     * Create a RedisCapsule resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: RedisCapsuleArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.name === undefined && !opts.urn) {
                throw new Error("Missing required property 'name'");
            }
            if (args?.spaceId === undefined && !opts.urn) {
                throw new Error("Missing required property 'spaceId'");
            }
            resourceInputs["cpuQty"] = args?.cpuQty;
            resourceInputs["cpuUnit"] = args?.cpuUnit;
            resourceInputs["description"] = args?.description;
            resourceInputs["memoryQty"] = args?.memoryQty;
            resourceInputs["memoryUnit"] = args?.memoryUnit;
            resourceInputs["name"] = args?.name;
            resourceInputs["replicas"] = args?.replicas;
            resourceInputs["spaceId"] = args?.spaceId;
            resourceInputs["storageQty"] = args?.storageQty;
            resourceInputs["storageUnit"] = args?.storageUnit;
            resourceInputs["privateConnectionString"] = undefined /*out*/;
            resourceInputs["privateHostname"] = undefined /*out*/;
            resourceInputs["privatePort"] = undefined /*out*/;
        } else {
            resourceInputs["cpuQty"] = undefined /*out*/;
            resourceInputs["cpuUnit"] = undefined /*out*/;
            resourceInputs["description"] = undefined /*out*/;
            resourceInputs["memoryQty"] = undefined /*out*/;
            resourceInputs["memoryUnit"] = undefined /*out*/;
            resourceInputs["name"] = undefined /*out*/;
            resourceInputs["privateConnectionString"] = undefined /*out*/;
            resourceInputs["privateHostname"] = undefined /*out*/;
            resourceInputs["privatePort"] = undefined /*out*/;
            resourceInputs["replicas"] = undefined /*out*/;
            resourceInputs["spaceId"] = undefined /*out*/;
            resourceInputs["storageQty"] = undefined /*out*/;
            resourceInputs["storageUnit"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["privateConnectionString"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(RedisCapsule.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a RedisCapsule resource.
 */
export interface RedisCapsuleArgs {
    /**
     * CPU request quantity.
     */
    cpuQty?: pulumi.Input<number>;
    /**
     * CPU request unit, e.g. "m". Defaults to "m".
     */
    cpuUnit?: pulumi.Input<string>;
    /**
     * The capsule's description. Mutable in place.
     */
    description?: pulumi.Input<string>;
    /**
     * Memory request quantity.
     */
    memoryQty?: pulumi.Input<number>;
    /**
     * Memory request unit, e.g. "M". Defaults to "M".
     */
    memoryUnit?: pulumi.Input<string>;
    /**
     * The capsule's name. Immutable after creation; changing it replaces the resource (renaming isn't supported).
     */
    name: pulumi.Input<string>;
    /**
     * Replica count. Defaults to 1.
     */
    replicas?: pulumi.Input<number>;
    /**
     * The owning Space's id. Immutable after creation; changing it replaces the resource.
     */
    spaceId: pulumi.Input<string>;
    /**
     * Storage request quantity.
     */
    storageQty?: pulumi.Input<number>;
    /**
     * Storage request unit, e.g. "Gi". Defaults to "Gi".
     */
    storageUnit?: pulumi.Input<string>;
}
