// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class WordpressCapsule extends pulumi.CustomResource {
    /**
     * Get an existing WordpressCapsule resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): WordpressCapsule {
        return new WordpressCapsule(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'codecapsules:index:WordpressCapsule';

    /**
     * Returns true if the given object is an instance of WordpressCapsule.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is WordpressCapsule {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === WordpressCapsule.__pulumiType;
    }

    declare public readonly cpuQty: pulumi.Output<number>;
    declare public readonly cpuUnit: pulumi.Output<string>;
    declare public readonly databaseName: pulumi.Output<string>;
    declare public readonly deploymentType: pulumi.Output<string>;
    declare public readonly description: pulumi.Output<string>;
    declare public readonly env: pulumi.Output<{[key: string]: string} | undefined>;
    declare public /*out*/ readonly hostname: pulumi.Output<string>;
    declare public readonly memoryQty: pulumi.Output<number>;
    declare public readonly memoryUnit: pulumi.Output<string>;
    declare public readonly mysqlCapsuleId: pulumi.Output<string>;
    declare public readonly name: pulumi.Output<string>;
    declare public readonly replicas: pulumi.Output<number>;
    declare public readonly spaceId: pulumi.Output<string>;
    declare public readonly storageCapsuleId: pulumi.Output<string>;
    declare public readonly storageQty: pulumi.Output<number>;
    declare public readonly storageUnit: pulumi.Output<string>;
    declare public readonly version: pulumi.Output<string>;

    /**
     * Create a WordpressCapsule resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: WordpressCapsuleArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.databaseName === undefined && !opts.urn) {
                throw new Error("Missing required property 'databaseName'");
            }
            if (args?.mysqlCapsuleId === undefined && !opts.urn) {
                throw new Error("Missing required property 'mysqlCapsuleId'");
            }
            if (args?.name === undefined && !opts.urn) {
                throw new Error("Missing required property 'name'");
            }
            if (args?.spaceId === undefined && !opts.urn) {
                throw new Error("Missing required property 'spaceId'");
            }
            if (args?.storageCapsuleId === undefined && !opts.urn) {
                throw new Error("Missing required property 'storageCapsuleId'");
            }
            resourceInputs["cpuQty"] = args?.cpuQty;
            resourceInputs["cpuUnit"] = args?.cpuUnit;
            resourceInputs["databaseName"] = args?.databaseName;
            resourceInputs["deploymentType"] = args?.deploymentType;
            resourceInputs["description"] = args?.description;
            resourceInputs["env"] = args?.env ? pulumi.secret(args.env) : undefined;
            resourceInputs["memoryQty"] = args?.memoryQty;
            resourceInputs["memoryUnit"] = args?.memoryUnit;
            resourceInputs["mysqlCapsuleId"] = args?.mysqlCapsuleId;
            resourceInputs["name"] = args?.name;
            resourceInputs["replicas"] = args?.replicas;
            resourceInputs["spaceId"] = args?.spaceId;
            resourceInputs["storageCapsuleId"] = args?.storageCapsuleId;
            resourceInputs["storageQty"] = args?.storageQty;
            resourceInputs["storageUnit"] = args?.storageUnit;
            resourceInputs["version"] = args?.version;
            resourceInputs["hostname"] = undefined /*out*/;
        } else {
            resourceInputs["cpuQty"] = undefined /*out*/;
            resourceInputs["cpuUnit"] = undefined /*out*/;
            resourceInputs["databaseName"] = undefined /*out*/;
            resourceInputs["deploymentType"] = undefined /*out*/;
            resourceInputs["description"] = undefined /*out*/;
            resourceInputs["env"] = undefined /*out*/;
            resourceInputs["hostname"] = undefined /*out*/;
            resourceInputs["memoryQty"] = undefined /*out*/;
            resourceInputs["memoryUnit"] = undefined /*out*/;
            resourceInputs["mysqlCapsuleId"] = undefined /*out*/;
            resourceInputs["name"] = undefined /*out*/;
            resourceInputs["replicas"] = undefined /*out*/;
            resourceInputs["spaceId"] = undefined /*out*/;
            resourceInputs["storageCapsuleId"] = undefined /*out*/;
            resourceInputs["storageQty"] = undefined /*out*/;
            resourceInputs["storageUnit"] = undefined /*out*/;
            resourceInputs["version"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["env"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(WordpressCapsule.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a WordpressCapsule resource.
 */
export interface WordpressCapsuleArgs {
    /**
     * CPU request quantity.
     */
    cpuQty?: pulumi.Input<number>;
    /**
     * CPU request unit, e.g. "m". Defaults to "m".
     */
    cpuUnit?: pulumi.Input<string>;
    /**
     * The database name to use on the referenced MysqlCapsule. Immutable after creation; changing it replaces the resource.
     */
    databaseName: pulumi.Input<string>;
    /**
     * Deployment type. Only "default" is supported; defaults to "default". Immutable after creation.
     */
    deploymentType?: pulumi.Input<string>;
    /**
     * The capsule's description. Mutable in place.
     */
    description?: pulumi.Input<string>;
    /**
     * Environment variables for the capsule. Replaces the full set on every change - useful for wiring in a RedisCapsule's connection details.
     */
    env?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    /**
     * Memory request quantity.
     */
    memoryQty?: pulumi.Input<number>;
    /**
     * Memory request unit, e.g. "M". Defaults to "M".
     */
    memoryUnit?: pulumi.Input<string>;
    /**
     * The id of an existing MysqlCapsule (must already be Ready) this site's database. Immutable after creation; changing it replaces the resource.
     */
    mysqlCapsuleId: pulumi.Input<string>;
    /**
     * The capsule's name. Immutable after creation; changing it replaces the resource (renaming isn't supported).
     */
    name: pulumi.Input<string>;
    /**
     * Replica count. Defaults to 1.
     */
    replicas?: pulumi.Input<number>;
    /**
     * The owning Space's id. Immutable after creation; changing it replaces the resource.
     */
    spaceId: pulumi.Input<string>;
    /**
     * The id of an existing StorageCapsule for this site's uploads/media. Immutable after creation; changing it replaces the resource.
     */
    storageCapsuleId: pulumi.Input<string>;
    /**
     * Storage request quantity.
     */
    storageQty?: pulumi.Input<number>;
    /**
     * Storage request unit, e.g. "Gi". Defaults to "Gi".
     */
    storageUnit?: pulumi.Input<string>;
    /**
     * The WordPress version to deploy. Required when deploymentType is "default". Immutable after creation; changing it replaces the resource.
     */
    version?: pulumi.Input<string>;
}
